<?php

/**
 * @file
 * Contains modern_js_drupal.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function modern_js_drupal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the modern_js_drupal module.
    case 'help.page.modern_js_drupal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module contains files for decoubled blocks with modern js libraries eg react/vue') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function modern_js_drupal_theme() {

  return [
    'modern_js_drupal' => [
      'render element' => 'children',
    ],

    'react_js_block' => [
      'variables' => [
        'node_title' => NULL,
      ],
      'template' => 'react-js-block',
    ],

    'vue_js_block' => [
      'variables' => [
        'node_title' => NULL,
      ],
      'template' => 'vue-js-block',
    ],
  ];
}
